// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7WT3HYNOZHnzQWSCNZSzR71Lo75a__RY',
    appId: '1:213157429142:web:20f337a1e7905e42b0e7b7',
    messagingSenderId: '213157429142',
    projectId: 'aplikasi-6a4a6',
    authDomain: 'aplikasi-6a4a6.firebaseapp.com',
    storageBucket: 'aplikasi-6a4a6.appspot.com',
    measurementId: 'G-J2YL4FBDS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FI0Ke5ObignGqsZEz6qubmB7fb_lUrE',
    appId: '1:213157429142:android:55772daf385f1ff9b0e7b7',
    messagingSenderId: '213157429142',
    projectId: 'aplikasi-6a4a6',
    storageBucket: 'aplikasi-6a4a6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7WT3HYNOZHnzQWSCNZSzR71Lo75a__RY',
    appId: '1:213157429142:web:67a31821ed9d6b66b0e7b7',
    messagingSenderId: '213157429142',
    projectId: 'aplikasi-6a4a6',
    authDomain: 'aplikasi-6a4a6.firebaseapp.com',
    storageBucket: 'aplikasi-6a4a6.appspot.com',
    measurementId: 'G-SL9ZFR6TDV',
  );
}
